const Certificate = require('../models/Certificate');
const Enrollment = require('../models/Enrollment');
const Course = require('../models/Course');
const User = require('../models/User');

// @desc    Generate certificate (Student - after completing course)
// @route   POST /api/certificates/:courseId
exports.generateCertificate = async (req, res) => {
  try {
    const studentId = req.user.id;
    const courseId = req.params.courseId;

    // Verify enrollment and completion
    const enrollment = await Enrollment.findOne({ studentId, courseId });
    if (!enrollment) {
      return res.status(404).json({ success: false, error: 'Not enrolled' });
    }

    if (enrollment.progressPercent < 100) {
      return res.status(400).json({ success: false, error: 'Course not completed' });
    }

    // Check if certificate already exists
    const existing = await Certificate.findOne({ studentId, courseId });
    if (existing) {
      return res.status(200).json({ success: true, data: existing });
    }

    const course = await Course.findById(courseId);
    const student = await User.findById(studentId).select('name');

    const certificate = await Certificate.create({
      studentId,
      courseId,
      // verificationCode is auto-generated by the model
    });

    // In production, you'd generate a PDF here and upload to Cloudinary
    // For now, we'll just store the verification code
    certificate.certificateUrl = `/verify/${certificate.verificationCode}`;
    await certificate.save();

    res.status(201).json({ success: true, data: certificate });
  } catch (err) {
    res.status(400).json({ success: false, error: err.message });
  }
};

// @desc    Get my certificates
// @route   GET /api/certificates/my
exports.getMyCertificates = async (req, res) => {
  try {
    const certificates = await Certificate.find({ studentId: req.user.id })
      .populate('courseId', 'title')
      .sort({ issuedAt: -1 });

    res.status(200).json({ success: true, data: certificates });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
};

// @desc    Verify certificate (PUBLIC - SECRET REQ #7)
// @route   GET /api/certificates/verify/:code
exports.verifyCertificate = async (req, res) => {
  try {
    const { code } = req.params;

    const certificate = await Certificate.findOne({ verificationCode: code })
      .populate('studentId', 'name')
      .populate('courseId', 'title');

    if (!certificate) {
      return res.status(404).json({ success: false, error: 'Certificate not found' });
    }

    res.status(200).json({
      success: true,
      data: {
        studentName: certificate.studentId.name,
        courseTitle: certificate.courseId.title,
        issuedAt: certificate.issuedAt,
        verificationCode: certificate.verificationCode
      }
    });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
};